### ISSUE TITLE
Kafka integration

### ISSUE THREAD

**Issue by rhuffus** [serverlesstechnology/cqrs-demo#5]
First, thank you very much for this project.
Are there any plans for integrating kafka as event store, something like "kafka-es"?
I have some experience with Kafka so I can help in that sense if needed.

**Comment by davegarred** [comment]
Hi @rhuffus,

Integration with Kafka should be fairly trivial as a query. No plans to add components but I'll add some documentation on ways to achieve it.

A simple implementation might look something like this:
```
struct KafkaEventForwarder {
    client: KafkaProducer
}

#[async_trait]
impl Query<BankAccount> for KafkaEventForwarder {
    async fn dispatch(&self, aggregate_id: &str, events: &[EventEnvelope<BankAccount>]) {
        for event in events {
            let payload = serde_json::to_vec(&event.payload).expect("unable to serialized payload");
            let record = KafkaRecord::new()
                .with_key(aggregate_id)
                .with_payload(&payload);
            self.client.send(record).await;
        }
    }
}
```

Ref [cqrs-es issue 14](https://github.com/serverlesstechnology/cqrs/issues/14)

**Comment by davegarred** [comment]
My apologies @rhuffus, I misread your question the first time.

An event-based storage platform is certainly tempting for an event store and I have considered the option. Kafka, however, is not designed as a permanent event store. Even though it can be configured to retain old events, there are likely some big downsides that would affect its' scalability and/or performance with very large tables.

Kafka is very useful, however, for event distribution, as I indicated in my previous comment. It works well to connect downstream queries with minimal load on the command processing server, giving a great deal of horizontal scalability. I've had a lot of success using this pattern in production systems. 

All that being said, if you have the inclination please do implement an EventStore, try it out and let me know what issues you might run into.
